spring.application.name=boardgames-shop

# INIT DATASOURCE
init.datasource.url=jdbc:postgresql://localhost:5432/postgres
init.datasource.username=postgres
init.datasource.password=TestSecret123

# DATASOURCE
spring.datasource.url=jdbc:postgresql://localhost:5432/boardgame_shop
spring.datasource.username=AdminRoma
spring.datasource.password=Roma21

# Hibernate / JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=ZininRomanVeryStrongSecretKeyForJwtTokenGeneration987654321
jwt.expiration-ms=86400000

# SQL
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

logging.level.org.springframework.security=DEBUG