-- =========================
-- TABLES
-- =========================

CREATE TABLE roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role_id BIGINT,
    CONSTRAINT fk_users_role FOREIGN KEY (role_id) REFERENCES roles(id)
);

CREATE TABLE clients (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    birth_date DATE,
    full_name VARCHAR(255),
    phone VARCHAR(255),
    user_id BIGINT UNIQUE,
    CONSTRAINT fk_clients_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE employees (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(255),
    phone VARCHAR(255),
    position VARCHAR(255),
    user_id BIGINT UNIQUE,
    CONSTRAINT fk_employees_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE games (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description VARCHAR(2000),
    name VARCHAR(255),
    price NUMERIC(38,2),
    active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    delivery_date TIMESTAMP,
    order_date TIMESTAMP,
    status VARCHAR(50),
    total_price NUMERIC(38,2),
    client_id BIGINT,
    employee_id BIGINT,
    CONSTRAINT fk_orders_client FOREIGN KEY (client_id) REFERENCES clients(id),
    CONSTRAINT fk_orders_employee FOREIGN KEY (employee_id) REFERENCES employees(id)
);

CREATE TABLE order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    price_at_purchase NUMERIC(38,2),
    quantity INTEGER,
    game_id BIGINT,
    order_id BIGINT,
    CONSTRAINT fk_items_game FOREIGN KEY (game_id) REFERENCES games(id),
    CONSTRAINT fk_items_order FOREIGN KEY (order_id) REFERENCES orders(id)
);